# This is prefixed to the key of each label that is added.
#TODO Restore prefix
iris_prefix: iris3
# labels are the keys we might use for each object, but only if
#_get<LABEL>() function is defined in the relevant plugin.
labels:
- name
- zone
- region
- location
- instance_type
#If enabled, then for each resource we are labeling, copy in the labels from its project.
from_project: True
#  Only these projects are included. If empty, all projects are included.
# TODO Restore (Replace with empty list)
projects:
- joshua-playground2
- joshua-playground-host-vpc
